services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - NODE_PORT=${NODE_PORT}
    volumes:
      - ..:/workspace:cached
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
